### ISSUE TITLE
Must extend Hoa\Ustring

### ISSUE THREAD

**Issue by Hywan** [hoaproject/String#1]
Related to https://github.com/hoaproject/Ustring/issues/28.

**Comment by Metalaka** [comment]
Should be tagged as `deprecated` in the README ?

**Comment by Hywan** [comment]
Yup, also. If you have time to do that, I would appreciate very much!

**Comment by Metalaka** [comment]
Can you add a new state `Deprecated.png` in [Central/Extra/Badges/Image](https://github.com/hoaproject/Central/tree/2b05123958/Extra/Badges/Image) ? (I can't convert svg with the same size/font as you :s)
And then we should make a **"warning"/deprecated** section before **Installation** section of the README.
I'll look for extend Ustring with String.

**Comment by Hywan** [comment]
@Metalaka http://central.hoa-project.net/State/String: ![state of Hoa\String](http://central.hoa-project.net/State/String). Now we have to wait Github cache to refresh.

**Comment by Metalaka** [comment]
Nice :)
